### ISSUE TITLE
Segmentation Fault: 11

### ISSUE THREAD

**Issue by github410117** [dayt0n/kairos#3]
Hi,
I follow the README， wrong
```
 ss$ ./kairos kernelcache.dec iBEC.patched -n -b "-v debug=0x09" -c "go" 0x830000300
[+] Patching kernelcache.dec
Segmentation fault: 11
```

kernelcache.dec is decrypted  and unpacked
version : iOS13.2.2
Thx

**Comment by dayt0n** [comment]
If you are using this on a kernelcache, it will not work. This tool is only for lower level images above SecureROM and below kernelcache.
