### ISSUE TITLE
13.4.1 BootLoader - iBSS / iBEC - Segmentation Fault 11

### ISSUE THREAD

**Issue by NotHereForTheDong** [dayt0n/kairos#4]
kairos ./iBSS.13.4.1.dec ibss.13.4.1.pat
[+] Patching ./iBSS.13.4.1.dec
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x2c66d
[+] Found IMG4 xref at 0xf0ec
[+] Found beginning of _image4_get_partial at 0xf07c
[+] Found xref to _image4_get_partial at 0x10694
[+] Found start of sub_1803905c8
[+] Found ADR X2, 0x1803b30ac at 0x30f2c
[+] Call to 0x7ffe7fc80000
Segmentation fault: 11

Kyles-MacBook-Air:ipad 13.1 kyletill$ kairos ./iBEC.13.4.1.dec ibec.13.4.1.pat.im4p
[+] Patching ./iBEC.13.4.1.dec
[+] Does have kernel load
[+] Enabling kernel debug...
[+] Found debug-enabled string at 0x47a2a
[+] Found debug-enabled xref at 0x11634
[+] Found second bl after debug-enabled xref at 0x11648
[+] Wrote MOVZ X0, #1 to 0x870011648
[+] Enabled kernel debug
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x478e5
[+] Found IMG4 xref at 0xf464
[+] Found beginning of _image4_get_partial at 0xf3f4
[+] Found xref to _image4_get_partial at 0x11374
[+] Found start of sub_870011234
[+] Found ADR X2, 0x87005369b at 0x4a510
[+] Call to 0xfffffff790000000
Segmentation fault: 11

This doesn't happen with other boot loaders such as 13.1

Test 13.1

kairos ./ibec.13.1.dec ibec.del
[+] Patching ./ibec.pat
[+] Does have kernel load
[+] Enabling kernel debug...
[+] Found debug-enabled string at 0x4a1c8
[+] Found debug-enabled xref at 0x1202c
[+] Found second bl after debug-enabled xref at 0x12084
[+] Wrote MOVZ X0, #1 to 0x870012084
[+] Enabled kernel debug
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x4a083
[+] Found IMG4 xref at 0xfc7c
[+] Found beginning of _image4_get_partial at 0xfbf0
[+] Found xref to _image4_get_partial at 0x10af4
[+] Found start of sub_8700108d4
[+] Found ADR X2, 0x87004b848 at 0x10c34
[+] Call to 0xff1c
[+] RET found for sub_87000ff1c at 0x1055c
[+] Did MOV r0, #0 and RET
[+] Wrote patched image to ibec.del

############

Seems to be replicated on two different Macs running Mojave and Catalina.

Specifics are iPad6,11 J71tap 13.4.1 iBSS and iBEC
Keys aren't on the wiki so here they are.

iBSS = Decrypting with s8003si GID key.
eb3e08750649eb98ca95d92878bac99b4d117078a1e06514cf8a8342366d2cae2b372acd34283968302c6cf299c3818d

iBEC = Decrypting with s8003si GID key.
f7a10fada9b3dae80afbc53450551686abbaf5935a82eb2cdb5495d8799989e3319a2f90a0cc893a61cad744d53a8931

**Comment by dayt0n** [comment]
I just pushed an update that should fix this issue. If you have any trouble please let me know.

**Comment by NotHereForTheDong** [comment]
This is now perfect thanks so much @dayt0n.

I appreciate the timely response and have always appreciated your work.


Kyles-MacBook-Air:ipad Test Kyle $ kairos ibss.dec ibss.pat
[+] Patching ibss.dec
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x2c66d
[+] Found IMG4 xref at 0xf0ec
[+] Found beginning of _image4_get_partial at 0xf07c
[+] Found xref to _image4_get_partial at 0xf9ac
[+] Found start of sub_18038f8cc
[+] Found ADR X2, 0x1803b2d88 at 0xfdd0
[+] Call to 0xf390
[+] RET found for sub_18038f390 at 0xf890
[+] Did MOV r0, #0 and RET
[+] Wrote patched image to ibss.pat
