### ISSUE TITLE
14.0 Beta1 - Segmentation fault: 11

### ISSUE THREAD

**Issue by NotHereForTheDong** [dayt0n/kairos#5]
iOS 14.0 Segmentation fault: 11 when patching ibss/ibec

kairos ibss.raw ibss.pat
[+] Patching ibss.raw
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x30184
[+] Found IMG4 xref at 0x1083c
[+] Found beginning of _image4_get_partial at 0x107cc
[+] Found xref to _image4_get_partial at 0x11248
[+] Found start of sub_1803c96b4
[+] Found ADR X2, 0x1803ef234 at 0x11658
[+] Call to 0xfffffffffffd8594
Segmentation fault: 11

kairos ibec.raw ibec.pat
[+] Patching ibec.raw
[+] Does have kernel load
[+] Enabling kernel debug...
[+] Found debug-enabled string at 0x4de10
[+] Found debug-enabled xref at 0x131bc
[+] Found second bl after debug-enabled xref at 0x131d0
[+] Wrote MOVZ X0, #1 to 0x8700738c0
[+] Enabled kernel debug
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x4dce3
[+] Found IMG4 xref at 0x10e64
[+] Found beginning of _image4_get_partial at 0x10df4
[+] Found xref to _image4_get_partial at 0x119cc
[+] Found start of sub_870071fdc
[+] Found ADR X2, 0x8700b0048 at 0x11f1c
[+] Call to 0xfffffffffffb0a18
Segmentation fault: 11

no keys publicly available so here they are.

iPad6,11 - J71tap

iBSS - Decrypting with s8003si GID key.
1a3192c05f2771c53684f1f2b9fd9fe3c96b94f7190c9b6967526be7ba7ecdade317dd5af2dade79b9fea54912c1df41

iBEC - Decrypting with s8003si GID key.
70549102334416c32d4f57d113c77c83bb0bd05ffc35b508ff247186e7793045f841ce43491361d9303cf7d8c957ca24

----------------------------------------------
Works on 13.4.1 for example
kairos ibec.raw  ibecTEST.pat -b "-v"
[+] Patching ibec.raw
[+] Does have kernel load
[+] Patching boot-args...
[+] Image base address at 0x870000000
[+] Searching for alternate boot-args
[+] Found boot-arg string at 0x47f32
[+] Found boot-arg xref at 0x12bfc
[+] Changed CSEL to MOV
[+] Found branch pointing to 0x870012cbc at 0x12bec
[+] Changed ADR X21, 0x870046900 to ADR X21, 0x870047f32
[+] Enabling kernel debug...
[+] Found debug-enabled string at 0x47a2a
[+] Found debug-enabled xref at 0x11634
[+] Found second bl after debug-enabled xref at 0x11648
[+] Wrote MOVZ X0, #1 to 0x870011648
[+] Enabled kernel debug
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x478e5
[+] Found IMG4 xref at 0xf464
[+] Found beginning of _image4_get_partial at 0xf3f4
[+] Found xref to _image4_get_partial at 0xfe58
[+] Found start of sub_87000fd78
[+] Found ADR X2, 0x8700490d0 at 0x1037c
[+] Call to 0xf708
[+] RET found for sub_87000f708 at 0xfcd4
[+] Did MOV r0, #0 and RET
[+] Wrote patched image to ibecTEST.pat

**Comment by dayt0n** [comment]
It should no longer segfault and *should* work for other iOS 14 beta builds. If you have any trouble, please let me know.

**Comment by NotHereForTheDong** [comment]
@dayt0n Thanks so much, it works great now.

kairos ibss.raw ibss.pat
[+] Patching ibss.raw
[+] Base address: 0x180380000
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x30184
[+] Found IMG4 xref at 0x1083c
[+] Found beginning of _image4_get_partial at 0x107cc
[+] Found xref to _image4_get_partial at 0x11248
[+] Found start of sub_180391168
[+] Found ADR X2, 0x1803b6ce8 at 0x11658
[+] Call to 0x10ae0
[+] RET found for sub_180390ae0 at 0x1112c
[+] Did MOV r0, #0 and RET
[+] Wrote patched image to ibss.pat
