### ISSUE TITLE
Possible iOS 9.x Support?

### ISSUE THREAD

**Issue by NotHereForTheDong** [dayt0n/kairos#6]
since the last update it seems that kairos can almost complete the patching on decrypted iOS 9 bootloader.

I don't think this is an easy task and if its not possible then let me know and I will close this as its not really an issue per-say, more of a future request.

this is the log on 9.3 iPhone 6,1

MacBook-Air:9.3 kyletill$ kairos iBSS.dec iBSS.pat
[+] Patching iBSS.dec
[+] Base address: 0x180380000
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x1c03f
[+] Found IMG4 xref at 0xa7e4
[+] Found beginning of _image4_get_partial at 0xa768
[!] Could not find correct xref for _image4_get_partial.
[!] RSA PATCH FAILED
[+] Wrote patched image to iBSS.pat

---------------------------------------------------------------------
This is the old log prior to the last update
[+] Patching iBSS.dec
[+] Base address: 0x180380000
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x1c03f
[+] Found IMG4 xref at 0xa7e4
[+] Found beginning of _image4_get_partial at 0xa768
[+] Found xref to _image4_get_partial at 0xac60
[+] Found start of sub_18038aa64
Segmentation fault: 11

in IDA sub_18038aa64 doesn't exist so I could see why it segfaults

**Comment by dayt0n** [comment]
Sorry for the long wait, but iOS 9 support should work as of 6cf0056. However, iOS 9 support is experimental. The RSA patch shouldn't cause you any trouble, but not sure how boot args will behave. Let me know if you have any issues with iOS 9 or with any other iOS version after this latest commit.

**Comment by NotHereForTheDong** [comment]
Wow, I can't thank you enough, I didn't expect this to happen and am extremely grateful that you took the time to implement iOS 9 support. The RSA patch is working perfectly as seen by the log below. 

P.S. The very minimal wait of ~20 days is nothing to apologize for, but rather something to boast about. The original goal was "C based iBoot64Patcher that worked on iOS 13" but has expanded beyond what iBoot64Patcher can do, this speaks to your skill and devotion and I sincerely appreciate it.


MacBook-Air:BUNDLES kyletill$ ./kairos iBEC.n51.RELEASE.im4p.dec iBEC.9.3.pat
[+] Patching iBEC.n51.RELEASE.im4p.dec
[+] Base address: 0x830000000
[+] Does have kernel load
[+] Enabling kernel debug...
[+] Found debug-enabled string at 0x2d4fe
[+] Found debug-enabled xref at 0xe59c
[+] Found second bl after debug-enabled xref at 0xe5c4
[+] Wrote MOVZ X0, #1 to 0x83000e5c4
[+] Enabled kernel debug
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x2d34e
[+] Found IMG4 xref at 0xcab8
[+] Found beginning of _image4_get_partial at 0xca30
[+] Found xref to _image4_get_partial at 0xce20
[+] Found start of sub_83000cd50
[+] Found ADR X2, 0x83000d8e0 at 0xd414
[+] Call to 0xd8e0
[+] RET found for sub_83000d8e0 at 0xdd60
[+] Did MOV r0, #0 and RET
[+] Wrote patched image to iBEC.9.3.pat


MacBook-Air:BUNDLES kyletill$ ./kairos iBSS.n51.RELEASE.im4p.dec iBSS.9.3.pat
[+] Patching iBSS.n51.RELEASE.im4p.dec
[+] Base address: 0x180380000
[+] Patching out RSA signature check...
[+] Found IMG4 string at 0x1fa92
[+] Found IMG4 xref at 0xa664
[+] Found beginning of _image4_get_partial at 0xa5dc
[+] Found xref to _image4_get_partial at 0xab0c
[+] Found start of sub_18038a8fc
[+] Found ADR X2, 0x18038b0bc at 0xac70
[+] Call to 0xb0bc
[+] RET found for sub_18038b0bc at 0xb53c
[+] Did MOV r0, #0 and RET
[+] Wrote patched image to iBSS.9.3.pat

**Comment by kocoman1** [comment]
Can this boot ramdisk ssh to fix activation error?

**Comment by dayt0n** [comment]
It's no problem! Always happy to improve the tool. 

Yeah, that was the original goal of this project, but I think it does have the potential to be expanded to include other patches for iBxxx in the future. Possibly even more than that.

Thanks!

**Comment by dayt0n** [comment]
> Can this boot ramdisk ssh to fix activation error?

You can use this tool to patch iBSS/iBEC and then boot your own custom SSH ramdisk if you want to access mostly system partition files. I am not too deep into the activation lock bypass scene though, so I may not be much help there.
