### ISSUE TITLE
error patching out RSA signature check

### ISSUE THREAD

**Issue by theIdeviceguy18383** [dayt0n/kairos#8]
[+] Patching ./iBEC
[+] Base address: 0xf8f9b2b253eed5a3
[+] Patching out RSA signature check...
[!] Could not find IMG4 string
[!] Error patching out RSA signature check
[+] Wrote patched image to ./ibec.patched
did i do something wrong?

**Comment by dayt0n** [comment]
What iOS version and device was this iBEC for? 

And is the image decrypted and unpacked?

**Comment by theIdeviceguy18383** [comment]
Oops forgot to decrypt before. Thank you!
